### PR TITLE
Initial User Story proposal

### LINKED ISSUE #5: Initial proposal for User Story of NumberRecycling API
**Problem description**

No User Story has yet been proposed
**Expected action**

A User Story proposal will be made.  Please discuss the proposal within this issue.

**Additional context**

### PR DESCRIPTION
**Pull request by yamamoto0104**
#### What type of PR is this?
* documentation

#### What this PR does / why we need it:
* Document user stories.

#### Which issue(s) this PR fixes:

Fixes #5 

#### Special notes for reviewers:
None

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Review by grgpapadopoulos — APPROVED** [review]

**Comment by eric-murray** [comment]
@yamamoto0104
Please include @camaraproject/number-recycling_maintainers as reviewers for any PRs in this sub-project. Thanks.

**Review by Masa8106 — DISMISSED** [review]
LGTM

**Comment by Masa8106** [comment]
@eric-murray 
Just for my clarification, is there any special reason to include "maintainers" as reviewers in this sub-project? This is because as far as I can remember I don't see sub-projects do that. Thank you.

**Review by grgpapadopoulos — DISMISSED** [review]

**Comment by eric-murray** [comment]
@Masa8106 
Asking for a review from maintainers is a way of bringing a PR to their attention, as maintainers will not necessarily be code owners. The github rules mean that their approval is not necessary to merge a PR (only one codeowner need approve for that to be allowed), but it is always useful to know if a maintainer approves a given PR as it shows that consensus has been reached. PRs should not be merged without reasonable steps to demonstrate consensus support.

Other APIs should be doing this for their PRs, and some do. The issue is that, once a single member of the maintainers group has reviewed, then github takes that review to represent the view of all maintainers and removes the maintainers group itself from the list of reviewers. So the maintainers group will only appear temporarily in the list of reviewers, and the approved PR will only list individual approvals.

**Comment by Masa8106** [comment]
@eric-murray 
Thank you for clarification. I understood.
I think it is good that PRs are reviewed by maintainers, even though it is not needed process.

**Comment by yamamoto0104** [comment]
@eric-murray 
I added @camaraproject/number-recycling_maintainers as reviewers based on your suggestion. Thank you.

**Review by luislopezcorpas — APPROVED** [review]

**Review by eric-murray — APPROVED** [review]

**Pull request merged**
